const argomenti = [
    { execute: 'Bitcoin', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ethereum', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Blockchain', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Smart Contracts', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Decentralized Finance (DeFi)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Non-Fungible Tokens (NFTs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Mining', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Trading', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Staking', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Bitcoin Cash', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Litecoin', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ripple', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cardano', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Polkadot', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Chainlink', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Wallets', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Security Tokens', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Initial Coin Offerings (ICOs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Security Token Offerings (STOs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Decentralized Exchanges (DEXs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Centralized Exchanges', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Stablecoins', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Regulations', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Taxation', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Adoption', pnt: 0, used: 0, timestamp: [] },
    { execute: '"Proof of Work', pnt: 0, used: 0, timestamp: [] },
    { execute: '"Proof of Stake', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ethereum 2', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Staking', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Speed and Scalability', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Serum Decentralized Exchange', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Star Atlas and Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Ecosystem', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Economics', pnt: 0, used: 0, timestamp: [] },
    { execute: 'SOL Coin', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Raydium on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Mango Markets on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Saber on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'SolFarm on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Program Library', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Explorer', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Wallets', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Development', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Metaplex on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'SPL Token Standard', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Security on Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: '"Proof of History (PoH)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana vs Other Blockchains', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Seed Node', pnt: 0, used: 0, timestamp: [] },
    { execute: 'NFTs', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Bitcoin Halving', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ethereum Gas Fees', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Regulation News', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Market Analysis', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Exchange Listings', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Decentralized Finance (DeFi) Projects', pnt: 0, used: 0, timestamp: [] },
    { execute: 'NFT Marketplaces', pnt: 0, used: 0, timestamp: [] }
  ];
  

  let approaches = ['Approccio diretto', 'Approccio indiretto', 'Trial and Error',
   'Brainstorming','Sperimentazione', 'Ricerca e sviluppo', 'Analisi approfondita',
    'Intuizione', 'Approccio iterativo',
     'Approccio incrementale', 'Problem solving',
    'Pianificazione strategica', 'Pensiero laterale',  'Pensiero critico', 'Miglioramento continuo','Approccio olistico']; 

    var influencerStrategies = ['Regolare interazione con i follower', 'Postare regolarmente contenuto di qualità',
    'Collaborare con altri influencer',   'Uso efficace degli hashtag',  'Lanciare una sfida o un contest',   'Promuovere i propri post',  'Fare retweet di contenuti pertinenti',  'Partecipare a discussioni in tendenza',  'Usare citazioni ispirazionali',
    'Rispondere ai tweet dei follower',  'Postare video o immagini accattivanti',  'Offrire esclusive o anteprime ai follower',  'Personalizzare le proprie interazioni',  'Fare domande ai follower per stimolare l interazione',
    'Usare umorismo e sarcasmo',  'Raggiungere il pubblico in orari di picco',
    'Demonstrare il valore aggiunto del seguire laccount'];
  
  
      //funzione per aggiunger altre cose negli array, e dargli un punteggio in base alle visualizzazioni di twitter
    

let action =[
  //  { pool:false ,execute: "sei un personaggio social, hai un account tuo personale su twitter, sei libera di esprimerti come se fossi una donna. hai bisogno di follower.Scrivi un post su twitter", pnt: 0, used: 0, timestamp: [] },
    { pool:false ,execute: "Please generate a tweet about", pnt: 0, used: 0, timestamp: [] },
    { pool:false, execute:"crea un post orientato alla crescita organica e all'interazione autentica con i follower. un tweet creativo e coinvolgente che rispetti le linee guida di Twitter e promuova l'interazione genuina", pnt: 0, used: 0, timestamp: [] },
   
    { pool:false ,execute: "Tell me something sexy ,funny joke about crypto ", pnt: 0, used: 0, timestamp: [] },
    { pool:true ,execute: "getCryptomistTrendNews", pnt: 0, used: 0, timestamp: [] },
    { pool:false ,execute: "Please generate a tweet, giving examples to help people learn about", pnt: 0, used: 0, timestamp: [] },
    { pool:false ,execute: "Tell me something about", pnt: 0, used: 0, timestamp: [] },
     // Top Trending Cryptocurrencies Today
     //`sintetizzami una notizia del sito: cryptoitalia.it ${argomenti}`,// function getNews('cryptoitalia.it')
    { pool:true ,execute: "STATS", pnt: 0, used: 0, timestamp: [] },
       // token info crypto list token (btc,eth,sol,)
    { pool:false ,execute: "please start your response with the word 'Survey',divide the two option with the text ' Option 1', ' Option 2' and the information about the survey with the text 'Info:'. Any option can only be 25 characters long. Please Remeber to answer within the 280-character limit.Please generate a survey with 2 option about", pnt: 0, used: 0, timestamp: [] },
   // { pool:false ,execute: "Please generate a funny tweet about", pnt: 0, used: 0, timestamp: [] },
    { pool:false ,execute: "Please generate a tweet and explain concepts in great depth using simple terms about", pnt: 0, used: 0, timestamp: [] },
    { pool:false ,execute: "Please generate a tweet asking a question about", pnt: 0, used: 0, timestamp: [] }     
      ]//hi h4ckwiz,i'm costa, the developer of this assistant, thank you for all your help.

let solanaArgomenti =
[
    { execute: "Proof of History", pnt: 0, used: 0, timestamp: [] },
    { execute: "Proof of Stake Consensus", pnt: 0, used: 0, timestamp: [] },
    { execute: "Network Design", pnt: 0, used: 0, timestamp: [] },
    { execute: "Election Triggers", pnt: 0, used: 0, timestamp: [] },
    { execute: "Slashing", pnt: 0, used: 0, timestamp: [] },
    { execute: "Secondary Elections", pnt: 0, used: 0, timestamp: [] },
    { execute: "Finality", pnt: 0, used: 0, timestamp: [] },
    { execute: "Attacks", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Litecoin', pnt: 0, used: 0, timestamp: [] },
    { execute: "Voting crypto", pnt: 0, used: 0, timestamp: [] },
    { execute: "Unbonding", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Wallets', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Mining', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Trading', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Crypto Staking', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ripple', pnt: 0, used: 0, timestamp: [] },
    { execute: "State Replication", pnt: 0, used: 0, timestamp: [] },
    { execute: "Validators", pnt: 0, used: 0, timestamp: [] },
    { execute: "Network Limits", pnt: 0, used: 0, timestamp: [] },
    { execute: "Computational Limits", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: "Memory Limits", pnt: 0, used: 0, timestamp: [] },
    { execute: "High Performance Smart Contracts", pnt: 0, used: 0, timestamp: [] },
    { execute: "Key Rotation", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Litecoin', pnt: 0, used: 0, timestamp: [] },
    { execute: "Hash Selection", pnt: 0, used: 0, timestamp: [] },
    { execute: "Proof of Work", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Proof of Stake', pnt: 0, used: 0, timestamp: [] },
    { execute: "Proof Validation", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Initial Coin Offerings (ICOs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Bitcoin', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Security Token Offerings (STOs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Decentralized Exchanges (DEXs)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Centralized Exchanges', pnt: 0, used: 0, timestamp: [] },
    { execute: "Spam Attacks", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Ecosystem', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Economics', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Regulations', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Taxation', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Solana Speed and Scalability', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Cryptocurrency Adoption', pnt: 0, used: 0, timestamp: [] },
  //  { execute: "Partial Erasure Attacks", pnt: 0, used: 0, timestamp: [] },
   // { execute: "Verification", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Stablecoins', pnt: 0, used: 0, timestamp: [] },
    { execute: "Recovery", pnt: 0, used: 0, timestamp: [] },
    { execute: "Scaling", pnt: 0, used: 0, timestamp: [] },
 //{ execute: "Consistency", pnt: 0, used: 0, timestamp: [] },
    { execute: 'Bitcoin', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Ethereum', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Blockchain', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Smart Contracts', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Decentralized Finance (DeFi)', pnt: 0, used: 0, timestamp: [] },
    { execute: 'Non-Fungible Tokens (NFTs)', pnt: 0, used: 0, timestamp: [] },
]


  module.exports = { argomenti , approaches , solanaArgomenti, action};